test: &default

  # Credentials for REST APIs
  client_id: ASGvpWjwPPC6bTX8HkkCz8Mlm8QLtLgt7h2pJpL10j_ItuJtSkjNcN1J-eXNvGFCxHloHrxGu8xnfFcH
  client_secret: EEJst--fxnpM1Z_b72YAmcR-rEuamZvbRa58nc9YZgJew4E9etCNh3vnntryFFpggF0CF5aB8raYmL8Y

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: productormusical93-facilitator-1@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
